#host = "127.0.0.1:8000"

[[nodes]]
name = "node_a"
cluster_address = "127.0.0.1:8000"
app_address = "127.0.0.1:9000"
public_address = "127.0.0.1:8080"

[[nodes]]
name = "node_b"
cluster_address = "127.0.0.1:8001"
app_address = "127.0.0.1:9001"
public_address = "127.0.0.1:8081"

[[nodes]]
name = "node_c"
cluster_address = "127.0.0.1:8002"
app_address = "127.0.0.1:9002"
public_address = "127.0.0.1:8082"
